using Content.Client.Message;
using Content.Client.UserInterface.Controls;
using Robust.Client.UserInterface.Controls;
using Content.Shared.Access.Components;
using Content.Shared.CCVar;
using Content.Shared.Security.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;
using Robust.Shared.Player;
using Content.Shared.Mobs.Components;
using Content.Shared.Access.Components;
using Content.Shared.Security.Components;
using Content.Shared.PDA;
using Content.Shared.Hands.EntitySystems;
using Content.Shared.Inventory;
using Robust.Shared.Configuration;

namespace Content.Client.Security.Ui;

[GenerateTypedNameReferences]
public sealed partial class GenpopLockerMenu : FancyWindow
{
    [Dependency] private readonly IConfigurationManager _cfgManager = default!;

    public event Action<string, float, string>? OnConfigurationComplete;

    public GenpopLockerMenu(EntityUid owner, IEntityManager entMan)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);


        Title = entMan.GetComponent<MetaDataComponent>(owner).EntityName;

        NameLabel.SetMarkup(Loc.GetString("genpop-locker-ui-label-name"));
        SentenceLabel.SetMarkup(Loc.GetString("genpop-locker-ui-label-sentence"));
        CrimeLabel.SetMarkup(Loc.GetString("genpop-locker-ui-label-crime"));

        SentenceEdit.Text = "5";
        CrimeEdit.Text = Loc.GetString("genpop-prisoner-id-crime-default");

        var maxIdJobLength = _cfgManager.GetCVar(CCVars.MaxIdJobLength);
        NameEdit.IsValid = val => !string.IsNullOrWhiteSpace(val) && val.Length <= maxIdJobLength;
        SentenceEdit.IsValid = val => float.TryParse(val, out var f) && f >= 0;
        CrimeEdit.IsValid = val => !string.IsNullOrWhiteSpace(val) && val.Length <= GenpopLockerComponent.MaxCrimeLength;

        NameEdit.OnTextChanged += _ => OnTextEdit();
        SentenceEdit.OnTextChanged += _ => OnTextEdit();
        CrimeEdit.OnTextChanged += _ => OnTextEdit();

        // Populate the dropdown/option selector with nearby ID information (short range).
        //
        // Strategy and rationale:
        // - We prefer to display the printed name on an ID card (crew ID) rather than the mob/entity display
        //   name because lockers should be assigned to identities found on physical IDs.
        // - Nearby entities may themselves be ID cards, PDAs that *contain* an ID (`PdaComponent.ContainedId`),
        //   a character holding an ID in their hands, or a character with an ID in their inventory `"id"` slot.
        // - We therefore enumerate nearby entities and attempt to resolve an ID-card entity for each candidate
        //   using a small helper (`FindIdCardEntity`). The helper returns the actual ID entity (which may be
        //   different from the candidate, e.g. a PDA's contained id) and a label string to display.
        // - Each `OptionButton` item stores the resolved ID entity's `EntityUid` as metadata so selection
        //   directly maps back to the exact ID entity (avoids relying on positional ordering).
        // - This entire process is best-effort on the client: systems may not be available or entities may
        //   be missing components. We wrap the lookup in try/catch and silently skip entries that cannot be
        //   resolved so the UI remains stable.
        try
        {
            var lookup = entMan.System<EntityLookupSystem>();
            const float range = 2.0f; // short distance
            var ents = lookup.GetEntitiesInRange(owner, range, LookupFlags.Dynamic | LookupFlags.Sundries);
            var id = 0;
            var handsSys = entMan.System<SharedHandsSystem>();
            var invSys = entMan.System<InventorySystem>();

            EntityUid? FindIdCardEntity(EntityUid candidate, out string? outLabel)
            {
                // Returns: the EntityUid of an ID-card entity (may be the candidate itself or an inner entity
                // such as a PDA's contained id) and an appropriate label to display on the option.
                // If nothing is found returns null and sets outLabel to null.
                outLabel = null;

                // 1) Direct ID card on the entity: common case when a loose ID card is on the ground.
                if (entMan.TryGetComponent<IdCardComponent>(candidate, out var directId))
                {
                    var meta = entMan.GetComponent<MetaDataComponent>(candidate);
                    // Prefer the printed FullName on the card if present, otherwise the entity's displayed name.
                    outLabel = directId.FullName ?? meta.EntityName;
                    return candidate;
                }

                // 2) Genpop-specific ID entity: these don't necessarily have a FullName field, so fall back
                //    to the entity display name.
                if (entMan.HasComponent<GenpopIdCardComponent>(candidate))
                {
                    var meta = entMan.GetComponent<MetaDataComponent>(candidate);
                    outLabel = meta.EntityName;
                    return candidate;
                }

                // 3) PDA that contains an ID: some PDAs embed an ID entity in `PdaComponent.ContainedId`.
                //    In that case prefer the contained id entity and its printed name.
                if (entMan.TryGetComponent<PdaComponent>(candidate, out var pda) && pda.ContainedId is { Valid: true } containedId)
                {
                    if (entMan.TryGetComponent<IdCardComponent>(containedId, out var idOnPda))
                    {
                        var meta = entMan.GetComponent<MetaDataComponent>(containedId);
                        outLabel = idOnPda.FullName ?? meta.EntityName;
                        return containedId;
                    }
                    if (entMan.HasComponent<GenpopIdCardComponent>(containedId))
                    {
                        var meta = entMan.GetComponent<MetaDataComponent>(containedId);
                        outLabel = meta.EntityName;
                        return containedId;
                    }
                }

                // 4) If the candidate is a character, check what they are holding (active hand) for an ID
                //    card or PDA containing an ID. This catches players who hold an ID or keep a PDA in hand.
                try
                {
                    var held = handsSys.GetActiveItem(candidate);
                    if (held is { Valid: true })
                    {
                        if (entMan.TryGetComponent<IdCardComponent>(held.Value, out var idHeld))
                        {
                            var meta = entMan.GetComponent<MetaDataComponent>(held.Value);
                            outLabel = idHeld.FullName ?? meta.EntityName;
                            return held.Value;
                        }
                        if (entMan.TryGetComponent<PdaComponent>(held.Value, out var heldPda) && heldPda.ContainedId is { Valid: true } heldContained && entMan.TryGetComponent<IdCardComponent>(heldContained, out var idOnHeldPda))
                        {
                            var meta = entMan.GetComponent<MetaDataComponent>(heldContained);
                            outLabel = idOnHeldPda.FullName ?? meta.EntityName;
                            return heldContained;
                        }
                        if (entMan.HasComponent<GenpopIdCardComponent>(held.Value))
                        {
                            var meta = entMan.GetComponent<MetaDataComponent>(held.Value);
                            outLabel = meta.EntityName;
                            return held.Value;
                        }
                    }
                }
                catch
                {
                    // Best-effort; ignore if hands system not available on this client build.
                }

                // 5) Check the character's inventory 'id' slot. Many characters store their ID in a dedicated
                //    slot (inventory slot named "id"). This can be an ID entity or a PDA that contains an ID.
                try
                {
                    if (invSys.TryGetSlotEntity(candidate, "id", out var slotEnt) && slotEnt is { Valid: true })
                    {
                        if (entMan.TryGetComponent<IdCardComponent>(slotEnt.Value, out var idSlot))
                        {
                            var meta = entMan.GetComponent<MetaDataComponent>(slotEnt.Value);
                            outLabel = idSlot.FullName ?? meta.EntityName;
                            return slotEnt.Value;
                        }
                        if (entMan.TryGetComponent<PdaComponent>(slotEnt.Value, out var slotPda) && slotPda.ContainedId is { Valid: true } slotContained && entMan.TryGetComponent<IdCardComponent>(slotContained, out var idOnSlotPda))
                        {
                            var meta = entMan.GetComponent<MetaDataComponent>(slotContained);
                            outLabel = idOnSlotPda.FullName ?? meta.EntityName;
                            return slotContained;
                        }
                        if (entMan.HasComponent<GenpopIdCardComponent>(slotEnt.Value))
                        {
                            var meta = entMan.GetComponent<MetaDataComponent>(slotEnt.Value);
                            outLabel = meta.EntityName;
                            return slotEnt.Value;
                        }
                    }
                }
                catch
                {
                    // Best-effort; ignore if inventory system not available on this client build.
                }

                // No ID found for this candidate.
                return null;
            }

            foreach (var e in ents)
            {
                if (e == owner)
                    continue;

                if (!entMan.TryGetComponent<MetaDataComponent>(e, out var meta))
                    continue;

                var idEntity = FindIdCardEntity(e, out var label);
                if (idEntity == null || string.IsNullOrWhiteSpace(label))
                    continue;

                NameSelector.AddItem(label, id);
                // Store the id card entity UID as metadata for this item.
                NameSelector.SetItemMetadata(NameSelector.ItemCount - 1, idEntity.Value);
                id++;
            }

            // Wire selection to populate the NameEdit while preserving manual typing.
            NameSelector.OnItemSelected += args =>
            {

                // Get the index for this id in the OptionButton and read the stored metadata (EntityUid).
                try
                {
                    var idx = NameSelector.GetIdx(args.Id);
                    var metaObj = NameSelector.GetItemMetadata(idx);
                    if (metaObj is EntityUid selectedEnt)
                    {
                        // Prefer the name printed on the ID card (IdCardComponent.FullName) when available.
                        if (entMan.TryGetComponent<IdCardComponent>(selectedEnt, out var selectedIdCard) && !string.IsNullOrWhiteSpace(selectedIdCard.FullName))
                        {
                            NameEdit.Text = selectedIdCard.FullName!;
                            OnTextEdit();
                        }
                        else if (entMan.TryGetComponent<MetaDataComponent>(selectedEnt, out var m2))
                        {
                            NameEdit.Text = m2.EntityName;
                            OnTextEdit();
                        }
                    }
                }
                catch
                {
                    // Best-effort: if anything fails, do nothing.
                }
            };
        }
        catch
        {
            // Best-effort only; if lookup/system isn't available on client, silently fail and leave the selector empty.
        }

        DoneButton.OnPressed += _ =>
        {
            OnConfigurationComplete?.Invoke(NameEdit.Text, float.Parse(SentenceEdit.Text), CrimeEdit.Text);
        };
    }

    private void OnTextEdit()
    {
        DoneButton.Disabled = string.IsNullOrWhiteSpace(NameEdit.Text) ||
                              !float.TryParse(SentenceEdit.Text, out var sentence) ||
                              sentence < 0 ||
                              string.IsNullOrWhiteSpace(CrimeEdit.Text);
    }
}
