using Content.Client.Message;
using Content.Client.UserInterface.Controls;
using Robust.Client.UserInterface.Controls;
using Content.Shared.Access.Components;
using Content.Shared.CCVar;
using Content.Shared.Security.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;
using Robust.Shared.Player;
using Content.Shared.Mobs.Components;
using Robust.Shared.Configuration;

namespace Content.Client.Security.Ui;

[GenerateTypedNameReferences]
public sealed partial class GenpopLockerMenu : FancyWindow
{
    [Dependency] private readonly IConfigurationManager _cfgManager = default!;

    public event Action<string, float, string>? OnConfigurationComplete;

    public GenpopLockerMenu(EntityUid owner, IEntityManager entMan)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);


        Title = entMan.GetComponent<MetaDataComponent>(owner).EntityName;

        NameLabel.SetMarkup(Loc.GetString("genpop-locker-ui-label-name"));
        SentenceLabel.SetMarkup(Loc.GetString("genpop-locker-ui-label-sentence"));
        CrimeLabel.SetMarkup(Loc.GetString("genpop-locker-ui-label-crime"));

        SentenceEdit.Text = "5";
        CrimeEdit.Text = Loc.GetString("genpop-prisoner-id-crime-default");

        var maxIdJobLength = _cfgManager.GetCVar(CCVars.MaxIdJobLength);
        NameEdit.IsValid = val => !string.IsNullOrWhiteSpace(val) && val.Length <= maxIdJobLength;
        SentenceEdit.IsValid = val => float.TryParse(val, out var f) && f >= 0;
        CrimeEdit.IsValid = val => !string.IsNullOrWhiteSpace(val) && val.Length <= GenpopLockerComponent.MaxCrimeLength;

        NameEdit.OnTextChanged += _ => OnTextEdit();
        SentenceEdit.OnTextChanged += _ => OnTextEdit();
        CrimeEdit.OnTextChanged += _ => OnTextEdit();

        // Populate the dropdown/option selector with nearby character names (short range).
        try
        {
            var lookup = entMan.System<EntityLookupSystem>();
            const float range = 2.0f; // short distance
            var ents = lookup.GetEntitiesInRange(owner, range, LookupFlags.Dynamic | LookupFlags.Sundries);
            var id = 0;
            foreach (var e in ents)
            {
                if (e == owner)
                    continue;

                // Include player-controlled entities and entities that are mobs (may have no player controller).
                if (!entMan.HasComponent<ActorComponent>(e) && !entMan.HasComponent<MobStateComponent>(e))
                    continue;

                if (!entMan.TryGetComponent<MetaDataComponent>(e, out var meta))
                    continue;

                var label = meta.EntityName;
                NameSelector.AddItem(label, id);
                // Store the entity UID as metadata for this item so selection maps directly to the entity.
                NameSelector.SetItemMetadata(NameSelector.ItemCount - 1, e);
                id++;
            }

            // Wire selection to populate the NameEdit while preserving manual typing.
            NameSelector.OnItemSelected += args =>
            {

                // Get the index for this id in the OptionButton and read the stored metadata (EntityUid).
                try
                {
                    var idx = NameSelector.GetIdx(args.Id);
                    var metaObj = NameSelector.GetItemMetadata(idx);
                    if (metaObj is EntityUid selectedEnt && entMan.TryGetComponent<MetaDataComponent>(selectedEnt, out var m2))
                    {
                        NameEdit.Text = m2.EntityName;
                        OnTextEdit();
                    }
                }
                catch
                {
                    // Best-effort: if anything fails, do nothing.
                }
            };
        }
        catch
        {
            // Best-effort only; if lookup/system isn't available on client, silently fail and leave the selector empty.
        }

        DoneButton.OnPressed += _ =>
        {
            OnConfigurationComplete?.Invoke(NameEdit.Text, float.Parse(SentenceEdit.Text), CrimeEdit.Text);
        };
    }

    private void OnTextEdit()
    {
        DoneButton.Disabled = string.IsNullOrWhiteSpace(NameEdit.Text) ||
                              !float.TryParse(SentenceEdit.Text, out var sentence) ||
                              sentence < 0 ||
                              string.IsNullOrWhiteSpace(CrimeEdit.Text);
    }
}
